---

name: Sync repo to Launchpad
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GIT_SSH_PRIVATE_KEY:
        required: true
      GIT_SSH_KNOWN_HOSTS:
        required: true
  push:


jobs:
  to_launchpad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://neovim-snap@git.launchpad.net/neovim-snap'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          #GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          DEBUG: "true"
